/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/chatscreen` | `/chatscreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboardscreen` | `/dashboardscreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/Staff` | `/Staff`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/Student` | `/Student`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/loginscreen` | `/loginscreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/registerscreen` | `/registerscreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/chatscreen` | `/chatscreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/dashboardscreen` | `/dashboardscreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/Staff` | `/Staff`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/Student` | `/Student`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/loginscreen` | `/loginscreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/registerscreen` | `/registerscreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/chatscreen${`?${string}` | `#${string}` | ''}` | `/chatscreen${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/dashboardscreen${`?${string}` | `#${string}` | ''}` | `/dashboardscreen${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/Staff${`?${string}` | `#${string}` | ''}` | `/Staff${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/Student${`?${string}` | `#${string}` | ''}` | `/Student${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/loginscreen${`?${string}` | `#${string}` | ''}` | `/loginscreen${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/registerscreen${`?${string}` | `#${string}` | ''}` | `/registerscreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/chatscreen` | `/chatscreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboardscreen` | `/dashboardscreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/Staff` | `/Staff`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/Student` | `/Student`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/loginscreen` | `/loginscreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/registerscreen` | `/registerscreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; };
    }
  }
}
